# Generated by Django 3.0.2 on 2020-02-03 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepost',
            name='totalviews',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
