# Generated by Django 3.0.2 on 2020-02-07 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_articlepost_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepost',
            name='profile',
            field=models.TextField(default=0),
        ),
    ]
