# Generated by Django 3.0.2 on 2020-02-04 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20200204_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(default='tfl', max_length=80, null=True),
        ),
    ]
